### ISSUE TITLE
Utilização da tag<Head> no app directory - deve utilizar Metadata API

### ISSUE THREAD

**Issue by caioalmeida12** [caioalmeida12/sisref-v2-dashboard#73]

**Comment by caioalmeida12** [comment]
Mensagem do console:
![image](https://github.com/caioalmeida12/sisref-v2-dashboard/assets/105614860/1d97e1c0-2bf4-4fd5-a117-f076e2411c8c)

Utilização no código (linha 14)
![image](https://github.com/caioalmeida12/sisref-v2-dashboard/assets/105614860/c0962d4b-32d2-4890-bda0-3ca2133a55b6)

**Comment by LuanF11** [comment]
> Mensagem do console: ![image](https://private-user-images.githubusercontent.com/105614860/325226367-1d97e1c0-2bf4-4fd5-a117-f076e2411c8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTQzMTUsIm5iZiI6MTcxNTAxNDAxNSwicGF0aCI6Ii8xMDU2MTQ4NjAvMzI1MjI2MzY3LTFkOTdlMWMwLTJiZjQtNGZkNS1hMTE3LWYwNzZlMjQxMWM4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQxNjQ2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDc5YzAxZmVlYTE0MDdjOWVlYzJkYmUyMjgwZWI2MzBhYTNkNDg4NDkyMWQyZjAxODVjYzIzZDE5ODk1YjQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.piWRpk54faCTbH6Iv_d2j9cSOJDhxvRz1504rNDHKkc)
> 
> Utilização no código (linha 14) ![image](https://private-user-images.githubusercontent.com/105614860/325226695-c0962d4b-32d2-4890-bda0-3ca2133a55b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTQzMTUsIm5iZiI6MTcxNTAxNDAxNSwicGF0aCI6Ii8xMDU2MTQ4NjAvMzI1MjI2Njk1LWMwOTYyZDRiLTMyZDItNDg5MC1iZGEwLTNjYTIxMzNhNTViNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQxNjQ2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDY3ZmU5Zjk1ZmZiMTYwOTNlZjQ3YTkwMDg1ZjgxYjRjMWM2ZDI1YjdmNWZiYWVmODczMGJmMDZjNTczY2IzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MT1HTwEYVSkBjrmIuKTmI7rTe-VHnCNHBP2gCqvaLwE)

Não deu erro nenhum aqui

**Comment by caioalmeida12** [comment]
Erro corrigido em outra pull request.
